vlog/app/noticias/urls.py
from django.conf.urls import url,include
from app.noticias.views import Listado_Noticias
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^listado_noticias$', Listado_Noticias.as_view(), name='listado_noticias'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

vlog/vlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^noticias/', include('app.noticias.urls', namespace="noticias")),
]

vlog/app/educacion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Educacion(models.Model):
    nombre_institucion = models.CharField(max_length=30,blank=True, null=True)
    temas_impartido = models.CharField(max_length=30,blank=True, null=True)
    fecha_de_seminario = models.DateTimeField(auto_now_add=False)
    def __unicode__(self):
		return '{}'.format(self.nombre_institucion)

vlog/app/noticias/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
# Create your models here.
import os

class Tematica(models.Model):
    nombre_tematica = models.CharField(max_length=30)
    def __unicode__(self):
		return '{}'.format(self.nombre_tematica)

def get_image_path(instance, filename):
    return os.path.join('media', str(instance.id), filename)


class Noticia(models.Model):
    autor = models.ForeignKey('auth.User', on_delete=models.CASCADE)#como el usuario que piblica 
    #la noticia
    titulo = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    texto = models.TextField()
    fecha_creado = models.DateTimeField(default=timezone.now)
    fecha_publicado = models.DateTimeField(blank=True, null=True)
    tematica = models.ForeignKey(Tematica,null=True, blank=True)#una noticia puede tener mas de 
	#una tematica, relacion de uno a muchos
    def __unicode__(self):
		return '{}'.format(self.titulo)

vlog/app/programacion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

vlog/app/educacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

vlog/app/noticias/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView
from app.noticias.models import Noticia,Tematica



class Listado_Noticias(ListView):
	ordering = ['id']   
	model = Noticia
	template_name = 'index_noticias.html'

# Create your views here.
def index_noticias(request):#con request  se le indica que reciba la peticion
	return render(request, 'index_noticias.html')

vlog/app/programacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

vlog/app/noticias/templates/index_noticias.html
{% extends 'home.html' %}
{% load staticfiles %}

     
{% block content %}

          
    <div class="container-fluid col-md-6 offset-1 ">
        {% if object_list %} {% for noticia in object_list %}
        <div class="card mb-4">
         <img src="{{noticia.imagen}}" ></img>
        <div class="card-body">

          <h2 class="card-title">{{noticia.titulo}}</h2>
          <p class="card-text">{{noticia.texto}}</p>
          <a href="https://bootsnipp.com/fullscreen/6Xa15" class="btn btn-primary">Leer mas...</a>
        </div>
        <div class="card-footer text-muted">
          {{noticia.fecha_publicado}} || Autor: {{noticia.autor}}
        </div>
      </div>
    
    <br>
    <br>
    <br>

   
    {%endfor%} {%else%}
        <H1>no hay noticias que mostrar</H1>
        
        
        
        {%endif%}

{% endblock content %}

{% block aside %}
<div id ="aside" class="container-fluid col-md-3 ">
<div class="card my-3 ">
    <center> <h5 class="card-header">Categorias</h5></center>
    <div class="card-body">
        
                <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                          {Cras justo odio}
                          <span class="badge badge-primary badge-pill">14</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                          Dapibus ac facilisis in
                          <span class="badge badge-primary badge-pill">2</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                          Morbi leo risus
                          <span class="badge badge-primary badge-pill">1</span>
                        </li>
                 </ul>
        </div>
      </div> 
      
      <div class="card my-3 ">
            <center> <h5 class="card-header">Recomendaciones</h5></center>
            <div class="card-body">
                
                        <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  {Cras justo odio}
                                  <span class="badge badge-primary badge-pill">14</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Dapibus ac facilisis in
                                  <span class="badge badge-primary badge-pill">2</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Morbi leo risus
                                  <span class="badge badge-primary badge-pill">1</span>
                                </li>
                         </ul>
                </div>
        </div>
<style>
    #aside {
      right:0;
      position: fixed;
      
    }
    </style> 
</div>

    </div>
    
{% endblock aside %}

vlog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% block title %}
    	<title>La puerta geek</title>

    {% endblock title %}
      
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<br><br> <br>
<body>
    <div class="row">

	{% block header %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <a class="navbar-brand" href="#">La puerta geek</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Inicio <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'noticias:listado_noticias' %}">Noticias</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Nuestra Programacion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Educacion</a>
          </li>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Acerca de...</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Buscar">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
        </form>
      </div>
  </nav>
	{% endblock header %}
    
	  
    {% block content %}
            
        <div class="container-fluid col-md-7 offset-1">
        <div class="alert-info">
		    <div class="jumbotron">
        <h1 class="display-3">La puerta geek</h1>
        <p class="lead">Una entrada al mundo de la ciencia y tecnologia.</p>
        <hr class="my-4">
        <p>Puedes recibir notificaciones sobre noticias y mas a tu correo.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">Registrate Aqui</a>
        </p>
      </div>
      </div>
      </div>
   

  {% endblock content %}

</body>

</div>
{% block aside %}

  
{% endblock aside %}

{% block footer %} 
<footer>
	<div id="footer" class="container-fluid fixed-bottom">
		<nav id="navbar-example2" class="navbar navbar-light bg-light">
				<a class="navbar-brand" href="#"><strong><h5> Creado por: Julio Dominguez</h5></strong></a>
				<ul class="nav nav-pills">
					<li class="nav-item">
						<a class="nav-link" href="#fat">@jdomcanal</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#mdo">Jdomcanal</a>
					</li>
					
			</div>
		</footer>
			{% endblock footer %}
</html>